[infolinks]
discord = "https://discord.gg/TFwswvDzJN"
github = "https://github.com/Pulsar-Lost-Colony/PulsarStation"

[game]
lobbyduration = 300
round_restart_time = 300
hostname = "☀ Pulsar - lost colony"
desc = "Эксперементальный русскоязычный сервер проекта Pulsar. Больше информации в нашем Discord."
soft_max_players = 100
maxplayers = 69

[server]
lobby_name = "☀ Pulsar - lost colony"
rules_file = "PulsarRuleset"

[ic]
flavor_text = true

[admin]
see_own_notes = true

[hub]
tags = "lang:ru"
